name: Get PR Number

on:
  workflow_call:
    outputs: 
      pr_number: 
        value: ${{ jobs.get_pr_number.outputs.output1 }}
   
jobs:
  get_pr_number:
    runs-on: ubuntu-24.04
    outputs:
      output1: ${{ steps.pr.outputs.pr_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR number
        id: pr
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          pr_number=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            | jq -r '.[0].number')
          echo "pr_number=${pr_number}"
          echo "pr_number=${pr_number}" >> $GITHUB_OUTPUT
